URL_SERVICE = "https://cnt-eb368bdf-a62c-457d-a192-60cb5c1e6bc3.containerhub.tripleten-services.com"
DOC_PATH = "/docs/"
LOG_MAIN_PATH = "/api/logs/main/"
CREATE_USER_PATH = "/api/v1/users/"
USERS_TABLE_PATH = "/api/db/resources/user_model.csv"